export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-emerald-50 to-white">
      <header className="container h-14 flex items-center justify-between border-b">
        <div className="flex items-center gap-2 font-extrabold tracking-tight">
          <img src="/khadyamqr-logo.svg" alt="KhadyamQR logo" className="h-8 w-8 rounded" />
          <span>KhadyamQR</span>
        </div>
        <a href="/" className="text-sm text-muted-foreground hover:text-foreground">← Back to Home</a>
      </header>

      <main className="container py-12 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        
        <div className="prose prose-emerald max-w-none space-y-6">
          <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>

          <section>
            <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p>By accessing and using KhadyamQR, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
            <p>KhadyamQR provides a platform for restaurants to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Create and manage digital menus</li>
              <li>Generate QR codes that link to their menus</li>
              <li>Upload and display menu item photos</li>
              <li>Update menu information in real-time</li>
              <li>Organize menu items by categories</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
            <p><strong>Admin Accounts:</strong></p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Can create and manage multiple restaurants</li>
              <li>Can generate QR codes</li>
              <li>Can create restaurant owner accounts</li>
              <li>Have full access to all features</li>
            </ul>
            <p className="mt-4"><strong>Restaurant Owner Accounts:</strong></p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Can manage their own restaurant's menu</li>
              <li>Can add, edit, and delete menu items</li>
              <li>Can toggle item availability</li>
              <li>Cannot create new restaurants or QR codes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">4. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide accurate and complete information</li>
              <li>Keep your login credentials secure</li>
              <li>Not share your account with others</li>
              <li>Not upload offensive, illegal, or copyrighted content</li>
              <li>Not attempt to hack or disrupt the service</li>
              <li>Comply with all applicable laws and regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">5. Content Ownership</h2>
            <p><strong>Your Content:</strong> You retain ownership of all content you upload (restaurant names, logos, menu items, photos, descriptions).</p>
            <p><strong>License to Us:</strong> By uploading content, you grant KhadyamQR a license to store, display, and distribute your content as necessary to provide the service.</p>
            <p><strong>Our Content:</strong> The KhadyamQR platform, logo, and software are owned by us and protected by copyright laws.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">6. Public Menus</h2>
            <p>Menu pages generated by KhadyamQR are publicly accessible via their unique URLs. Anyone with the URL can view your menu. Do not include sensitive or private information in your menu.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">7. Service Availability</h2>
            <p>We strive to provide reliable service, but we do not guarantee:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Uninterrupted access to the service</li>
              <li>Error-free operation</li>
              <li>That the service will meet your specific requirements</li>
            </ul>
            <p className="mt-4">We may suspend or terminate the service for maintenance, updates, or other reasons with or without notice.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">8. Prohibited Uses</h2>
            <p>You may not use KhadyamQR to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Violate any laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Upload malicious code or viruses</li>
              <li>Spam or harass other users</li>
              <li>Scrape or copy content without permission</li>
              <li>Resell or redistribute the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">9. Termination</h2>
            <p>We reserve the right to suspend or terminate your account if you:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Violate these Terms of Service</li>
              <li>Engage in fraudulent activity</li>
              <li>Upload prohibited content</li>
              <li>Fail to pay applicable fees (if any)</li>
            </ul>
            <p className="mt-4">You may terminate your account at any time by contacting us.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">10. Limitation of Liability</h2>
            <p>KhadyamQR is provided "as is" without warranties of any kind. We are not liable for:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Loss of data or content</li>
              <li>Business interruption or lost profits</li>
              <li>Indirect, incidental, or consequential damages</li>
              <li>Actions of third parties</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">11. Indemnification</h2>
            <p>You agree to indemnify and hold KhadyamQR harmless from any claims, damages, or expenses arising from your use of the service or violation of these terms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">12. Changes to Terms</h2>
            <p>We may modify these Terms of Service at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">13. Governing Law</h2>
            <p>These terms are governed by the laws of [Your Jurisdiction]. Any disputes will be resolved in the courts of [Your Jurisdiction].</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">14. Contact Information</h2>
            <p>For questions about these Terms of Service:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Email: legal@khadyamqr.com</li>
              <li>Contact Form: <a href="/contact" className="text-primary hover:underline">/contact</a></li>
            </ul>
          </section>
        </div>
      </main>

      <footer className="container py-10 text-sm text-muted-foreground border-t">
        © {new Date().getFullYear()} KhadyamQR. All rights reserved.
      </footer>
    </div>
  );
}
